"""organization pipeline runs

Revision ID: 8c08da3b521c
Revises: eadaab8c0d84
Create Date: 2020-10-26 14:15:14.496981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c08da3b521c"
down_revision = "eadaab8c0d84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_processing_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_pipeline_input_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=200), server_default="", nullable=False),
        sa.Column("organization_pipeline_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_pipeline_id"],
            ["organization_pipeline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_pipeline_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("organization_pipeline_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_uuid", sa.String(length=32), nullable=False),
        sa.Column(
            "post_processing_pipeline_run_uuid",
            sa.String(length=32),
            server_default="",
            nullable=False,
        ),
        sa.Column("status_update_token", sa.String(length=32), nullable=False),
        sa.Column("status_update_token_expires_at", sa.DateTime(), nullable=False),
        sa.Column("share_token", sa.String(length=32), nullable=False),
        sa.Column("share_password_hash", sa.String(length=127), nullable=False),
        sa.Column("share_password_salt", sa.String(length=127), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_pipeline_id"],
            ["organization_pipeline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_pipeline_run_post_processing_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("organization_pipeline_run_id", sa.Integer(), nullable=False),
        sa.Column("post_processing_state_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_pipeline_run_id"],
            ["organization_pipeline_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_processing_state_id"],
            ["post_processing_state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_pipeline_run_post_processing_state")
    op.drop_table("organization_pipeline_run")
    op.drop_table("organization_pipeline_input_file")
    op.drop_table("post_processing_state")
    # ### end Alembic commands ###
