# A system that has the same dependencies of the main project, and docker as
# well.

FROM presencepg/presence-workflow

RUN apt install -y apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common \
  && \
  apt-get clean

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt update
RUN apt install -y docker-ce
