export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_IN_PROGRESS = 'CREATE_USER_IN_PROGRESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_IN_PROGRESS = 'AUTH_IN_PROGRESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const REFRESH_JWT = 'REFRESH_JWT';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_ORGANIZATIONS = 'GET_USER_ORGANIZATIONS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
export const GET_USER_ORGANIZATIONS_FAILED = 'GET_USER_ORGANIZATIONS_FAILED';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_IN_PROGRESS = 'UPDATE_USER_PROFILE_IN_PROGRESS';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';
export const GET_USER_AVATAR = 'GET_USER_AVATAR';
export const GET_USER_AVATAR_FAILED = 'GET_USER_AVATAR_FAILED';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_USER_AVATAR_FAILED = 'UPDATE_USER_AVATAR_FAILED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_IN_PROGRESS = 'CHANGE_PASSWORD_IN_PROGRESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_ORGANIZATION = 'CHANGE_ORGANIZATION';
export const RETURN_TO_SETTINGS_CONFIRMED = 'RETURN_TO_SETTINGS_CONFIRMED';

export const GET_PIPELINES = 'GET_PIPELINES';
export const GET_PIPELINES_FAILED = 'GET_PIPELINES_FAILED';

export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';

export const GET_PIPELINE_RUNS = 'GET_PIPELINE_RUNS';
export const GET_PIPELINE_RUNS_FAILED = 'GET_PIPELINE_RUNS_FAILED';
export const GET_PIPELINE_RUN = 'GET_PIPELINE_RUN';
export const GET_PIPELINE_RUN_FAILED = 'GET_PIPELINE_RUN_FAILED';

export const UPLOAD_INPUT_FILE = 'UPLOAD_INPUT_FILE';
export const UPLOAD_INPUT_FILE_FAILED = 'UPLOAD_INPUT_FILE_FAILED';
export const REMOVE_INPUT_FILE = 'REMOVE_INPUT_FILE';
export const CLEAR_INPUT_FILES = 'CLEAR_INPUT_FILES';

export const GET_CHARTS = 'GET_CHARTS';
export const GET_CHARTS_FAILED = 'GET_CHARTS_FAILED';
export const ADD_CHART = 'ADD_CHART';
export const ADD_CHART_FAILED = 'ADD_CHART_FAILED';
export const PROCESS_ARTIFACT = 'PROCESS_ARTIFACT';
export const PROCESS_ARTIFACT_FAILED = 'PROCESS_ARTIFACT_FAILED';

export const GET_ORGANIZATION_MEMBERS = 'GET_ORGANIZATION_MEMBERS';
export const GET_ORGANIZATION_MEMBERS_FAILED = 'GET_ORGANIZATION_MEMBERS_FAILED';
export const GET_ORGANIZATION_INVITATIONS = 'GET_ORGANIZATION_INVITATIONS';
export const GET_ORGANIZATION_MEMBERS_INVITATIONS_FAILED = 'GET_ORGANIZATION_MEMBERS_INVITATIONS_FAILED';
export const REMOVE_ORGANIZATION_MEMBER = 'REMOVE_ORGANIZATION_MEMBER';
export const REMOVE_ORGANIZATION_MEMBER_FAILED = 'REMOVE_ORGANIZATION_MEMBER_FAILED';
export const CHANGE_ORGANIZATION_MEMBER_ROLE = 'CHANGE_ORGANIZATION_MEMBER_ROLE';
export const CHANGE_ORGANIZATION_MEMBER_ROLE_FAILED = 'CHANGE_ORGANIZATION_MEMBER_ROLE_FAILED';
export const INVITE_ORGANIZATION_MEMBER = 'INVITE_ORGANIZATION_MEMBER';
export const INVITE_ORGANIZATION_MEMBER_FAILED = 'INVITE_ORGANIZATION_MEMBER_FAILED';
export const ACCEPT_ORGANIZATION_INVITATION = 'ACCEPT_ORGANIZATION_INVITATION';
export const ACCEPT_ORGANIZATION_INVITATION_FAILED = 'ACCEPT_ORGANIZATION_INVITATION_FAILED';
