export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_IN_PROGRESS = 'AUTH_IN_PROGRESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const REFRESH_JWT = 'REFRESH_JWT';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_ORGANIZATIONS = 'GET_USER_ORGANIZATIONS';
export const CHANGE_ORGANIZATION = 'CHANGE_ORGANIZATION';

export const GET_PIPELINES_STARTED = 'GET_PIPELINES_STARTED';
export const GET_PIPELINES_COMPLETED = 'GET_PIPELINES_COMPLETED';
export const GET_PIPELINES_FAILED = 'GET_PIPELINES_FAILED';

export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';

export const GET_ORGANIZATION_MEMBERS = 'GET_ORGANIZATION_MEMBERS';
export const REMOVE_ORGANIZATION_MEMBER = 'REMOVE_ORGANIZATION_MEMBER';
export const REMOVE_ORGANIZATION_MEMBER_FAILED = 'REMOVE_ORGANIZATION_MEMBER_FAILED';
export const CHANGE_ORGANIZATION_MEMBER_ROLE = 'CHANGE_ORGANIZATION_MEMBER_ROLE';
export const CHANGE_ORGANIZATION_MEMBER_ROLE_FAILED = 'CHANGE_ORGANIZATION_MEMBER_ROLE_FAILED';
