export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_PIPELINES_STARTED = 'GET_PIPELINES_STARTED';
export const GET_PIPELINES_COMPLETED = 'GET_PIPELINES_COMPLETED';
export const GET_PIPELINES_FAILED = 'GET_PIPELINES_FAILED';

export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';
