from blob_utils.constants import *

SECRET_KEY = "SECRET_KEY"
SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
CELERY_BROKER_URL = "CELERY_BROKER_URL"
CELERY_ALWAYS_EAGER = "CELERY_ALWAYS_EAGER"
MAX_CONTENT_LENGTH = "MAX_CONTENT_LENGTH"
WORKER_API_SERVER = "WORKER_API_SERVER"
WORKER_API_TOKEN = "WORKER_API_TOKEN"
CALLBACK_TIMEOUT = 100
S3_PRESIGNED_TIMEOUT = "S3_PRESIGNED_TIMEOUT"