from blob_utils.constants import *

# Configurable application keys:
SECRET_KEY = "SECRET_KEY"
SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
MAX_CONTENT_LENGTH = "MAX_CONTENT_LENGTH"
AUTH_HOSTNAME = "AUTH_HOSTNAME"
WORKFLOW_HOSTNAME = "WORKFLOW_HOSTNAME"
WORKFLOW_API_TOKEN = "WORKFLOW_API_TOKEN"
