"""artifact_chart_is_deleted_nullable

Revision ID: 172616be1a28
Revises: bbaf6bedc4c6
Create Date: 2020-12-09 20:17:32.813230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172616be1a28'
down_revision = 'bbaf6bedc4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_chart', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_chart', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
