"""input file to pipeline run

Revision ID: 34c2fcfd8aed
Revises: c0de2a9adaca
Create Date: 2020-11-12 14:37:15.869805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34c2fcfd8aed'
down_revision = 'c0de2a9adaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('workflow_uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_workflow_pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_workflow_uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('organization_pipeline_id', sa.Integer(), nullable=False),
    sa.Column('workflow_pipeline_uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_pipeline_id'], ['organization_pipeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_workflow_pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_workflow_id', sa.Integer(), nullable=False),
    sa.Column('organization_pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_uuid', sa.String(length=32), server_default='', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_pipeline_run_id'], ['organization_pipeline_run.id'], ),
    sa.ForeignKeyConstraint(['organization_workflow_id'], ['organization_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('artifact_chart', 'chart_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('organization_pipeline_input_file', sa.Column('organization_pipeline_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization_pipeline_input_file', 'organization_pipeline_run', ['organization_pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_pipeline_input_file', type_='foreignkey')
    op.drop_column('organization_pipeline_input_file', 'organization_pipeline_run_id')
    op.alter_column('artifact_chart', 'chart_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('organization_workflow_pipeline_run')
    op.drop_table('organization_workflow_pipeline')
    op.drop_table('organization_workflow')
    # ### end Alembic commands ###
