"""added delete pipeline run

Revision ID: 5246af75af33
Revises: 870eb100922d
Create Date: 2021-02-09 21:43:35.116226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5246af75af33'
down_revision = '870eb100922d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelinerun', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelinerun', 'is_deleted')
    # ### end Alembic commands ###
