"""add_input_file_pipeline_run_uuid

Revision ID: cffe83c29d00
Revises: bbfac1d325be
Create Date: 2020-11-11 01:04:04.844576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffe83c29d00'
down_revision = 'bbfac1d325be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_pipeline_input_file', sa.Column('organization_pipeline_run_uuid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_pipeline_input_file', 'organization_pipeline_run_uuid')
    # ### end Alembic commands ###
