"""add_input_file_array_on_pipeline_run

Revision ID: e53a1b7d4c64
Revises: bbfac1d325be
Create Date: 2020-11-10 00:21:49.687651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53a1b7d4c64'
down_revision = 'bbfac1d325be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_pipeline_run', sa.Column('pipeline_run_input_file_uuids', sa.String(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_pipeline_run', 'pipeline_run_input_file_uuids')
    # ### end Alembic commands ###
