# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "openfido-remote-state"
    dynamodb_table = "openfido-remote-state-lock"
    encrypt        = true
    key            = "enviroments/stage/data-storage/postgreSQL/terraform.tfstate"
    profile        = "openfido-stage"
    region         = "us-east-1"
  }
}
