# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "openfido-remote-state"
    dynamodb_table = "openfido-remote-state-lock"
    encrypt        = true
    key            = "enviroments/dev/services/front_end/terraform.tfstate"
    profile        = "openfido"
    region         = "us-east-1"
  }
}
